import os

def display():
    os.system("clear")
    print("Navigation functions")
    print("")
    print("For executing any shell command please enter : followed by the command string.")
    print("For example enter :ls -l to list the contents of the current directory in detail.")
    print("")
    print("")
    print("Other useful navigation options:")
    print("")
    print(":-    -  repeat last executed shell command (if any)")
    print(":     -  enter a shell command based on previous command")
    print(":<    -  enter command history menu")
    print("::    -  enter command history menu to edit a previous command")
    print("::<>   -  clear command history")
    print("<     -  enter history menu")
    print(">     -  enter favorites menu")
    print(",     -  go to the previously visited directory")
    print("+>    -  add current directory to favorites")
    print("->    -  remove a directory from favorites")
    print(":<>   -  clear navigation history")
    print("")
    print("For direct navigation to a history or favorites menu entry please enter < or > followed by a number.")
    print("Please do not put any spaces between operator and number.")
    print("")
    print("Current directory: "+os.getcwd())
    print("")
    print("Enter the path of the directory you want to visit (press ENTER to return to the home dir).")
    print("Enter ! to quit navigation mode.")
    print("")
